# environment 
# [Production, Development, and Local]
environment: Development
fully_qualified_domain_name: ""

# horde deployment
deployment:
  # replica count
  replicaCount: 1
  
  # strategy 
  strategy:
  #    type: RollingUpdate
  #    rollingUpdate:
  #      maxSurge: 0
  #      maxUnavailable: 1
  
  metadata:
    annotations: { }
    labels: { }
  
  # horde container
  container:
    name: "unreal-horde-container"
    
    # image info
    image:
      name: "ghcr.io/epicgames/horde-server"
      tag: "latest-bundled"
      pullPolicy: IfNotPresent
    
    # Service account, if empty the service account will be created
    serviceAccount: ""
    
    terminationGracePeriodSeconds: 30
    
    resources: { }
      #  limits:
      #    cpu: 1
      #    memory: 4Gi
      #  requests:
      #    cpu: 1
    #    memory: 4Gi
    
    # name: environment variable name
    # 
    env: [ ]
    # - name: environment variable name
    #   value: environment variable value
    envFromSecrets: [ ]
    #  - secretName
    envFromConfigMaps: [ ]
    #  - configMapName
    
    # container lifecycle hooks
    lifecycle: {}
    #  preStop:
    #    exec:
    #      command: ["/bin/sh", "-c", "sleep 10"]

# service settings
service:
  http:
    type: LoadBalancer
    port: 5000
    annotations: { }
    labels: { }
  grpc:
    type: LoadBalancer
    port: 5002
    annotations: { }
    labels: { }

# ingress settings  
ingress:
  enabled: false
  className: ""
  annotations: { }
  labels: { }
  rules: [ ]

# auth settings
auth:
  authMethod: ""
  oidcAuthority: ""
  oidcAudience: ""
  oidcClientId: ""
  oidcClientSecret: ""
  oidcSigninRedirect: ""
  adminClaimType: ""
  adminClaimValue: ""

# Horde configuration json file location
configPath: ""

# Perforce settings  
perforce:
  server: ""
  trust_servers: []
  # TODO: support getting this from existing secret
  username: ""
  password: ""

# redis (or elasticache) settings
redis:
  # TODO: support spinning up redis in a subchart
  external: true
  host: ""
  port: 6379

# mongodb (or documentdb) settings
mongodb:
  # TODO: support spinning up mongodb in a subchart
  external: true
  install_documentdb_cert: true
  # TODO: support getting this from existing secret
  host: ""
  port: 0
  # leave off the question mark
  connectionArgs: ""
  username: ""
  password: ""