{{- if .Values.mongodb.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mongodb-secret
  namespace: {{ .Chart.Name }}
data:
  Horde__databaseConnectionString: {{ printf "mongodb://%s:%s@%s:%d?%s" .Values.mongodb.username .Values.mongodb.password .Values.mongodb.host .Values.mongodb.port .Values.mongodb.connectionArgs | b64enc | quote }}
{{- end }}