{{- if .Values.mongodb.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}MongoDBSecret
  namespace: {{ .Chart.Name }}
data:
  Horde__databaseConnectionString: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}?{{ .Values.mongodb.connectionArgs }}"
  {{- if .Values.mongodb.install_documentdb_cert }}
  Horde__databasePublicCert: "/app/config/global-bundle.pem"
  {{- end }}
{{- end }}